package com.evoreview.context.parse;

import com.evoreview.context.model.FileCategory;

import java.util.Locale;
import java.util.Set;

/**
 * Classifies changed files so that generated artifacts, binaries, and lockfiles
 * never reach the AST or packing stages. Content-based generated detection uses
 * only a small sample (first few KB), never the whole file.
 */
public final class ChangeClassifier {

    private static final Set<String> BINARY_EXT = Set.of(
            "png", "jpg", "jpeg", "gif", "webp", "ico", "bmp", "pdf", "zip", "tar", "gz",
            "jar", "war", "class", "exe", "dll", "so", "dylib", "woff", "woff2", "ttf",
            "eot", "mp4", "mp3", "db", "sqlite", "bin", "dat");

    private static final Set<String> SOURCE_EXT = Set.of(
            "java", "kt", "kts", "scala", "groovy", "py", "js", "jsx", "ts", "tsx", "mjs",
            "cjs", "go", "rs", "c", "h", "cc", "cpp", "cxx", "cs", "rb", "php", "swift",
            "m", "mm", "sql", "sh", "bash", "ps1", "vue");

    private static final Set<String> CONFIG_EXT = Set.of(
            "yml", "yaml", "xml", "json", "toml", "ini", "properties", "cfg", "conf", "gradle");

    private static final Set<String> DOC_EXT = Set.of("md", "markdown", "adoc", "rst", "txt");

    private static final Set<String> LOCK_FILE_NAMES = Set.of(
            "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "composer.lock",
            "go.sum", "cargo.lock", "gemfile.lock", "poetry.lock");

    private static final Set<String> GENERATED_MARKERS = Set.of(
            "do not edit", "@generated", "auto-generated", "autogenerated",
            "automatically generated", "generated by");

    public FileCategory classify(String path, String contentSample) {
        String lower = path.toLowerCase(Locale.ROOT);
        String name = basename(lower);
        String ext = extension(name);

        if (BINARY_EXT.contains(ext)) {
            return FileCategory.BINARY;
        }
        if (isGenerated(lower, name, contentSample)) {
            return FileCategory.GENERATED;
        }
        if (isTest(lower, name)) {
            return FileCategory.TEST;
        }
        if (DOC_EXT.contains(ext)) {
            return FileCategory.DOCUMENTATION;
        }
        if (CONFIG_EXT.contains(ext) || isConfigName(name)) {
            return FileCategory.CONFIG;
        }
        if (SOURCE_EXT.contains(ext)) {
            return FileCategory.SOURCE;
        }
        return FileCategory.OTHER;
    }

    private boolean isGenerated(String lowerPath, String name, String contentSample) {
        if (LOCK_FILE_NAMES.contains(name)
                || name.endsWith(".min.js") || name.endsWith(".min.css")
                || name.endsWith(".pb.go") || name.endsWith("_pb2.py")
                || name.endsWith(".designer.cs") || name.endsWith(".g.cs")
                || lowerPath.contains("/generated/") || lowerPath.contains("/gen/")) {
            return true;
        }
        if (contentSample != null && !contentSample.isEmpty()) {
            String sample = contentSample.toLowerCase(Locale.ROOT);
            return GENERATED_MARKERS.stream().anyMatch(sample::contains);
        }
        return false;
    }

    private boolean isTest(String lowerPath, String name) {
        return lowerPath.contains("src/test/")
                || lowerPath.contains("/test/") || lowerPath.contains("/tests/")
                || name.endsWith("test.java") || name.endsWith("tests.java") || name.endsWith("it.java")
                || name.startsWith("test_") || name.endsWith("_test.py") || name.endsWith("_test.go")
                || name.contains(".test.") || name.contains(".spec.");
    }

    private boolean isConfigName(String name) {
        return name.equals("pom.xml") || name.equals("dockerfile") || name.equals("makefile")
                || name.equals(".gitignore") || name.equals(".editorconfig");
    }

    private static String basename(String path) {
        int slash = path.lastIndexOf('/');
        return slash < 0 ? path : path.substring(slash + 1);
    }

    private static String extension(String name) {
        int dot = name.lastIndexOf('.');
        return dot <= 0 ? "" : name.substring(dot + 1);
    }
}
