package com.evoreview.context.parse;

import com.evoreview.context.model.FileCategory;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import static org.assertj.core.api.Assertions.assertThat;

class ChangeClassifierTest {

    private final ChangeClassifier classifier = new ChangeClassifier();

    @ParameterizedTest
    @CsvSource({
            "src/main/java/Foo.java, SOURCE",
            "frontend/app/App.vue, SOURCE",
            "scripts/deploy.sh, SOURCE",
            "src/test/java/FooTest.java, TEST",
            "FooTest.java, TEST",
            "foo_test.py, TEST",
            "app/App.test.ts, TEST",
            "app/App.spec.js, TEST",
            "package-lock.json, GENERATED",
            "client.pb.go, GENERATED",
            "foo_pb2.py, GENERATED",
            "ui/app.min.js, GENERATED",
            "build/gen/Client.java, GENERATED",
            "settings.yml, CONFIG",
            "pom.xml, CONFIG",
            "backend/Dockerfile, CONFIG",
            "README.md, DOCUMENTATION",
            "docs/guide.rst, DOCUMENTATION",
            "logo.png, BINARY",
            "dist/app.jar, BINARY",
            "data.unknownext, OTHER"
    })
    void classifiesByPath(String path, FileCategory expected) {
        assertThat(classifier.classify(path, null)).isEqualTo(expected);
    }

    @Test
    void detectsGeneratedByContentMarker() {
        String sample = "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pb;";
        assertThat(classifier.classify("src/main/java/rpc/ServiceGrpc.java", sample))
                .isEqualTo(FileCategory.GENERATED);
    }

    @Test
    void normalSourceFileWithInnocentContentIsNotGenerated() {
        String sample = "package com.example;\n\npublic class Foo {}\n";
        assertThat(classifier.classify("src/main/java/Foo.java", sample))
                .isEqualTo(FileCategory.SOURCE);
    }

    @Test
    void binaryWinsOverEverythingElse() {
        assertThat(classifier.classify("src/test/resources/image.png", "DO NOT EDIT"))
                .isEqualTo(FileCategory.BINARY);
    }
}
